#!/bin/sh
# Vercel production env listesi — .env.local değerlerini Vercel dashboard'a ekleyin.
# Kullanım: sh scripts/vercel-env-checklist.sh

echo ""
echo "=========================================="
echo "  Vercel Environment Variables Checklist"
echo "=========================================="
echo ""
echo "Vercel → Project → Settings → Environment Variables"
echo "Production + Preview + Development için ekleyin:"
echo ""
echo "  DATABASE_URL                   (sslmode=require önerilir)"
echo "  NEXT_PUBLIC_APP_NAME"
echo "  NEXT_PUBLIC_APP_DESCRIPTION"
echo "  NEXT_PUBLIC_APP_URL            → https://YOUR_DOMAIN"
echo "  NEXT_PUBLIC_SITE_URL           → https://YOUR_DOMAIN"
echo "  NEXT_PUBLIC_ROOT_DOMAIN        → YOUR_DOMAIN"
echo "  NEXT_PUBLIC_CANONICAL_HOST     → YOUR_DOMAIN"
echo ""
echo "  Sosyal medya (footer — isteğe bağlı):"
echo "  NEXT_PUBLIC_INSTAGRAM_URL"
echo "  NEXT_PUBLIC_FACEBOOK_URL"
echo "  NEXT_PUBLIC_TWITTER_URL"
echo "  NEXT_PUBLIC_YOUTUBE_URL"
echo ""
echo "  Mobil mağaza (isteğe bağlı):"
echo "  NEXT_PUBLIC_APP_STORE_URL"
echo "  NEXT_PUBLIC_PLAY_STORE_URL"
echo ""
echo "  Özellik bayrakları (isteğe bağlı):"
echo "  WALLET_ENABLED=false"
echo "  SCRAPER_ENABLED=false"
echo ""
echo "  NEXT_PUBLIC_FIREBASE_API_KEY"
echo "  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
echo "  NEXT_PUBLIC_FIREBASE_PROJECT_ID"
echo "  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
echo "  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
echo "  NEXT_PUBLIC_FIREBASE_APP_ID"
echo "  FIREBASE_SERVICE_ACCOUNT_JSON    (firebase-admin.json tek satır)"
echo ""
echo "  Güvenlik (ZORUNLU — production):"
echo "  NEXTAUTH_SECRET                (openssl rand -base64 48)"
echo "  TICKET_SECRET_KEY              (openssl rand -base64 48) — oturumdan AYRI"
echo "  SUPER_ADMIN_EMAILS             → admin@example.com"
echo "  CRON_SECRET                    (openssl rand -base64 32)"
echo "  ADMIN_SECRET                   (openssl rand -base64 32) — yıkıcı admin otomasyonu"
echo ""
echo "  Rate limiting (önerilir — production):"
echo "  UPSTASH_REDIS_REST_URL         (Upstash console → REST API)"
echo "  UPSTASH_REDIS_REST_TOKEN"
echo ""
echo "  E-posta (önerilir):"
echo "  RESEND_API_KEY"
echo "  RESEND_FROM_NAME               → BiletFeed"
echo "  RESEND_FROM_EMAIL              → tickets@biletfeed.com"
echo "  RESEND_REPLY_TO                → destek@biletfeed.com"
echo ""
echo "  Muhasebe (önerilir):"
echo "  ACCOUNTING_VAT_RATE            → 20"
echo "  COMPANY_IBAN"
echo "  COMPANY_MERSIS_NO"
echo ""
echo "  Ödeme (iyzico onayı sonrası):"
echo "  PAYMENT_PROVIDER=iyzico"
echo "  IYZICO_API_KEY"
echo "  IYZICO_SECRET_KEY"
echo "  IYZICO_BASE_URL                → https://api.iyzipay.com"
echo "  ASLA production'da: ENABLE_MOCK_PAYMENTS=true"
echo ""
echo "Deploy:"
echo "  npx vercel login"
echo "  npx vercel --prod"
echo ""
echo "Production DB (bir kez):"
echo "  DATABASE_URL=\"...\" npm run db:setup"
echo "  (schema + şehir/kategori seed + etkinlik kuralları kataloğu)"
echo ""
echo "Production seed (alternatif — cron):"
echo "  CRON_TARGET_URL=https://YOUR_DOMAIN/api/cron/seed-event-rules npm run cron:trigger"
echo "  veya Admin → Ayarlar → Etkinlik Kurallarını Seed Et"
echo ""
echo "Kurulum doğrulama:"
echo "  npm run setup:check"
echo ""
